# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='address',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
